### ISSUE TITLE
command-line tool for admetsar

### ISSUE THREAD

**Issue by smruti241** [zealseeker/admetsar2-doc#2]
Hii,
I have gone through all the data and paper of admetsar. Actually, the thing is that I have some 11 crore compounds for which I need ADMET information. I found admetsar fine for this prediction, but it is web-service based. Can you please tell me how to run it in command-line? Please help me regarding this. Thank you

**Comment by zealseeker** [comment]
Sorry, we don't have a command-line tool for prediction.

**Comment by smruti241** [comment]
Then how this tool can be run in command line?

**Comment by zealseeker** [comment]
We don't have API so that you cannot use command line to access these models. Sorry for that.
Our webserver supports batch prediction, so it is easy to predict your core compounds. But if you are aware of IP issues, we can do little for that. We won't collect any query compound, but we cannot guarantee the privacy. If you do want to predict them "safely", a good way is to contact Prof. Yun Tang.

**Comment by smruti241** [comment]
Can you please tell me the download link for ADMET from DrugBank? How did you download the compounds from drugbank?

**Comment by zealseeker** [comment]
You can download Drugbank via this link https://go.drugbank.com/releases/latest 
Close it since it seems to be solved.
